### ISSUE TITLE
Dataset removed

### ISSUE THREAD

**Issue by benoit-cty** [mtobeiyf/ava_downloader#1]
Hello,

The url http://www.lucamarchesotti.com/ava/download/start_download.html is dead.

It seems to exist a similar dataset here : https://drive.google.com/drive/u/0/folders/0BxeylfSgpk1MOVduWGxyVlJFUHM (Source : https://github.com/aimerykong/deepImageAestheticsAnalysis )

Hope this could help someone else..

**Comment by imfing** [comment]
Thanks, 
I've downloaded AADB before 😄 
Fortunately, I got the list of AVA before the link was dead, here is the AVA dataset file: [Google Drive](https://drive.google.com/open?id=0B_vctR3Pe7PvQmVnYUJyTU9ZcDg)
However, it is still a tough work to fetch all the 250,000+ images from dpchallenge.com 🤒

**Comment by benoit-cty** [comment]
Nice, thank you !

**Comment by benoit-cty** [comment]
There is a link to a Mega archive of the dataset here : https://www.reddit.com/r/MachineLearning/comments/5sa3ag/r_image_aestetics_dataset_avadpchallenge/ (32GB)

**Comment by imfing** [comment]
Yes, I've downloaded that. Thanks!
