### ISSUE TITLE
Missing zip files from the provided link.

### ISSUE THREAD

**Issue by Kousis** [mtobeiyf/ava_downloader#10]
Hi mtobeiyf,
It seems that some zip files are missing from the provided link. I can see only the 1,59 and 62 parts there.

**Comment by imfing** [comment]
Use [this link](https://mega.nz/folder/9b520Lzb#2gIa1fgAzr677dcHKxjmtQ) instead:

**Comment by Kousis** [comment]
Thanks!

**Comment by imfing** [comment]
Just updated the README. Please let me know if you have any issue downloading the dataset.
