### ISSUE TITLE
Could you please send me the subset of fall down ？

### ISSUE THREAD

**Issue by wwdok** [mtobeiyf/ava_downloader#11]
Hi, bro, now i am only care about the `fall down` subset of this dataset , and because the total dataset is too big and most of them is not useful for me, so in order to save the disk space and download time,  could you please send me the subset of fall down if you are convinient ？Thanks ！

By the way, from your side, can you view the Entities in the explore page ? (https://research.google.com/ava/explore.html)

![image](https://user-images.githubusercontent.com/43233772/98782589-3a997680-2433-11eb-91c9-fed7370360b2.png)

**Comment by imfing** [comment]
Hey bro, this AVA is not that "AVA".
