### ISSUE TITLE
Processing archive: images.7z

### ISSUE THREAD

**Issue by seyeeet** [mtobeiyf/ava_downloader#12]
can someone help me here.
I donwload the 64 images.7z but I cannot extract them
![image](https://user-images.githubusercontent.com/62394093/98874697-c073ec80-2448-11eb-8730-c46b7a23b81f.png)

**Comment by imfing** [comment]
See #8

**Comment by seyeeet** [comment]
first I did this
`7zr x '*.7z*'` and it gave me `images.7z` . and it shows:
```
7-Zip (A) [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,16 CPUs)

Processing archive: images.7z.001

Extracting  images.7z

Everything is Ok

Size:       33129205390
Compressed: 524288000

```
but I'm not sure how to extract the files from `images.7z`

no matter what I do I get this:
```
Processing archive: images.7z

Error: Can not open file as archive

```

**Comment by imfing** [comment]
I'm not sure. Please Google and see what's wrong with your commands. I think you should directly extract rather than combine it as a `images.7z` file.

**Comment by seyeeet** [comment]
the main issue was from academic torrent, the files were damaged, I had to ask a friend for dataset, if you can upload them somewhere else.

**Comment by imfing** [comment]
You can always download from the mega drive, which should work.
