### ISSUE TITLE
Incorrect label ratings

### ISSUE THREAD

**Issue by RaduFilip16** [mtobeiyf/ava_downloader#13]
Some labels from the AVA.txt are not on a scale of 1 to 10. Why is that?
<img width="314" alt="incorrect labels" src="https://user-images.githubusercontent.com/80462618/177387117-67d53003-4b6d-43ef-b08f-8cad183b69e5.png">

**Comment by imfing** [comment]
Hi @RaduFilip16 

Please take a look at the metadata readme file:

https://github.com/imfing/ava_downloader/blob/69a0c8b0f9a0c7bfff1a8efdad80a53c599a6f0d/AVA_dataset/README.txt#L32-L33

It's the count in a scale from 1 to 10.

**Comment by RaduFilip16** [comment]
I'm sorry but I still don't get it. I moved the content to an excel file for a better explanation. So as I understand column 3/C should have the number of ratings of 1 and column L/12 the number of ratings of 10 but shouldn't everything in between them have scores from 1 to 10?
<img width="785" alt="incorrect labels2" src="https://user-images.githubusercontent.com/80462618/177529096-ef742c8a-5a02-47fb-a8d4-4b4179d6f962.png">

**Comment by imfing** [comment]
the red line there, from column D to K, are # of rating 2, 3, 4, ..., 9, respectively.

so it's the **count** of users who gave 1, 2, 3, ..., 10 rating for each image, not the **score** itself.

**Comment by RaduFilip16** [comment]
Oh, now I get it. Thank you very much!
