### ISSUE TITLE
Downloading the data from mega, I have to download all the files and merge them?

### ISSUE THREAD

**Issue by created-Bi** [mtobeiyf/ava_downloader#14]
When I tried to open the file using 7z x images.7z.001, an open error happend: Can not open the file as [7z] archive

![image](https://github.com/imfing/ava_downloader/assets/28759055/29f8f3ef-2337-4838-a007-8bf4bbbaa2f6)

So I have to download all the files and merge them to one final file and then unzip?

**Comment by imfing** [comment]
Yes you need to download all of the files
