### ISSUE TITLE
New download source on HuggingFace

### ISSUE THREAD

**Issue by IceClear** [mtobeiyf/ava_downloader#16]
Given the fact that it may not be convenient to download AVA dataset from MEGA Cloud, I have provided the resource on [HuggingFace](https://huggingface.co/datasets/Iceclear/AVA).
Hoping this can help.

**Comment by geekyme** [comment]
Thanks for this @IceClear! Saw the dataset is only 16.2GB on HuggingFace. I thought the original dataset was 32GB according to [here](https://github.com/imfing/ava_downloader?tab=readme-ov-file#dataset-download)?

> The entire dataset has been split into 64 7z files. Download all the zip files, unzip the first file and it should work. About 32GB and 255,500 picture files.

**Comment by geekyme** [comment]
I think this source is better -> https://www.kaggle.com/datasets/nicolacarrassi/ava-aesthetic-visual-assessment?resource=download

**Comment by IceClear** [comment]
> Thanks for this @IceClear! Saw the dataset is only 16.2GB on HuggingFace. I thought the original dataset was 32GB according to [here](https://github.com/imfing/ava_downloader?tab=readme-ov-file#dataset-download)?
> 
> > The entire dataset has been split into 64 7z files. Download all the zip files, unzip the first file and it should work. About 32GB and 255,500 picture files.

Thanks for your reminder. The files are originally from the MEGA source. But I forgot the details. I may have a check later and update the files.

**Comment by imfing** [comment]
@geekyme @IceClear thanks for all these new options!
this repo is half of a decade old so Mega may not be a good choice anymore.

Let me know what I can help to make AVA more accessible to more people 😄

**Comment by geekyme** [comment]
I tried the kaggle download link I shared above. It works well so maybe you can update the readme for that in case another person stumble on this repo 🤓

**Comment by IceClear** [comment]
> > Thanks for this @IceClear! Saw the dataset is only 16.2GB on HuggingFace. I thought the original dataset was 32GB according to [here](https://github.com/imfing/ava_downloader?tab=readme-ov-file#dataset-download)?
> > > The entire dataset has been split into 64 7z files. Download all the zip files, unzip the first file and it should work. About 32GB and 255,500 picture files.
> 
> Thanks for your reminder. The files are originally from the MEGA source. But I forgot the details. I may have a check later and update the files.

The file has been updated and I think the AVA dataset on HF is also available now. This is particularly convenient for downloading directly using the command.

**Comment by imfing** [comment]
@IceClear @geekyme Thank you, I've updated the README with the new sources. 👍
