### ISSUE TITLE
有时候无法下载

### ISSUE THREAD

**Issue by aijianiula0601** [mtobeiyf/ava_downloader#3]
有时候能下载，又是不能下载，是什么原因的？要翻墙？

**Comment by aijianiula0601** [comment]
我debug了下代码，看到下载一段时间之后“<h1>Attention</h1><p>Page cannot be served due to suspicious activity detected from your address”
那个网站有反爬虫，不让下载？

**Comment by imfing** [comment]
@aijianiula0601 是的，你爬不断向网站发送请求的话ip会被封一段时间的。我在README里面有写到

> With this script keep sending requests to dpchallenge.com, the website would block your ip address for some time. 

建议你直接下载README最上面的链接里面的压缩包，包含了AVA的25万张图片。
