### ISSUE TITLE
按照 README.md上去MEG下载的图片无法解压

### ISSUE THREAD

**Issue by aijianiula0601** [mtobeiyf/ava_downloader#4]
第一个文件 名为：images.7z.001 ，怎么解压呢，我是mac下用7z去解压，并不能解压出来，也用windows的7z软件入解压，同样解压不出来。请问你们是怎么弄的呢

**Comment by imfing** [comment]
@aijianiula0601 你好，你需要把所有的压缩包（而不是仅仅是一个）全部下载下来才能正确解压。
