### ISSUE TITLE
have no access to the Dataset download link

### ISSUE THREAD

**Issue by linrjing** [mtobeiyf/ava_downloader#6]
Is there something wrong with the link "https://mega.nz/#F!hIEhQTLY" or "https://mega.nz/#!MUcXyBSB". I have no access to these links. I want to download the AVA data for the image quality study. Is there any available link ?

**Comment by imfing** [comment]
@linrjing I checked, they are available. The reason why you couldn't visit is your network condition. If you can visit Google, then you can visit those links.

**Comment by linrjing** [comment]
Hi fing,
I've tried but failed. I can visit google and download image from imageNet successfully. Is there any other links?

**Comment by imfing** [comment]
@linrjing Probably the reason you can access google is that you have ipv6. 
A VPN or something like this is necessary. Visit the link under the proxy which located in US or other places. Mega is blocked by the GFW.
