### ISSUE TITLE
What is the version of the ava dataset from Mega link

### ISSUE THREAD

**Issue by xiaoyuliu** [mtobeiyf/ava_downloader#7]
Hi,

Thanks for the great effort! Can you tell us which version is provided by the Mega link? Since `ava_train_2.0` and `ava_val_2.0` are already released.

Thanks.

**Comment by imfing** [comment]
😂 
I guess you mistake this for another [AVA](https://research.google.com/ava/)  **published by google** ([AVA: A Video Dataset of Spatio-temporally Localized Atomic Visual Actions](https://arxiv.org/abs/1705.08421))

**This AVA** stands for [A Large-Scale Database for Aesthetic Visual Analysis](http://ieeexplore.ieee.org/document/6247954/), which is a image dataset for visual analysis.

But I can provide some help if you really needed. 😄 

BTW, 学姐你好呀~

**Comment by xiaoyuliu** [comment]
What a sad news.....
Thank you!!

哈哈哈学弟你好，扎心了，那我再找找

**Comment by imfing** [comment]
我简单看了一下，一共好像有几百个 youtube 的 id
可以用 [videoder](https://www.videoder.net/online-video-downloader) 或者 github 上的其它人写的命令行工具去下载
但我随便看了两个，原始的视频都挺长的，有些 id 对应的视频还没法访问 😂 
这个 repo 有视频 [google-AVA-Dataset-downloader](https://github.com/SmartPorridge/google-AVA-Dataset-downloader)，不过好像没有更新到 2.0

**Comment by xiaoyuliu** [comment]
是哒，我也看到了那个repo，里面提到googlet提供了ava_cache但是网页不存在了....
不行就用百度云下吧

**Comment by xiaoyuliu** [comment]
btw, 学弟太厉害了！

**Comment by imfing** [comment]
学姐也超棒啦 😆 
对了，我今年暑假要到BC省去做暑研。还想请教学姐一下经验啦~

**Comment by xiaoyuliu** [comment]
没问题啊,我微信发邮件给你
