### ISSUE TITLE
unzip 7z fail

### ISSUE THREAD

**Issue by PaulChongPeng** [mtobeiyf/ava_downloader#8]
Centos 7.0 or macos 10.12.6

$ 7za x images.7z.001

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,40 CPUs Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (406F1),ASM,AES-NI)

Scanning the drive for archives:
1 file, 524288000 bytes (500 MiB)

Extracting archive: images.7z.001
ERROR: images.7z.001
images.7z
Open ERROR: Can not open the file as [7z] archive

ERRORS:
Unexpected end of archive

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

7z x images.7z.001

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 524288000 bytes (500 MiB)

Extracting archive: images.7z.001
ERROR: images.7z.001
images.7z
Open ERROR: Can not open the file as [7z] archive

ERRORS:
Unexpected end of archive
    
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

**Comment by imfing** [comment]
You need to download all 7z files and there are 64 of them.
After that, you could extract them.

**Comment by PaulChongPeng** [comment]
I have downloaded 64 7z files , but failed to extract it

**Comment by imfing** [comment]
Perhaps you should use the right command
https://superuser.com/questions/463154/is-it-a-requirement-to-concatenate-multiple-7zip-files-in-linux-before-being-abl/463380
https://askubuntu.com/questions/134227/how-to-extract-files-from-a-split-7zip-archive

**Comment by PaulChongPeng** [comment]
Thanks！ I have found the reason that one file is damaged，and I download it again

**Comment by imfing** [comment]
Okay, that's great.

**Comment by jl1914** [comment]
How to find which file is damaged?
Or could you please upload the MD5 for each file?
Thanks
